#!/bin/bash
# This script prints a JSON blob that describes each of the Terra workspaces to which the currently-authenticated gcloud user has access.

curl -k -X 'GET' 'https://api.firecloud.org/api/workspaces' -H 'accept: application/json' -H "Authorization: Bearer $(gcloud auth print-access-token)"
