requires 'Amazon::S3', '0.45';
requires 'JSON', '4.02';
requires 'JSON::XS', '4.02';
requires 'Text::CSV', '2.00';
requires 'LWP::Protocol::https', '6.09';
requires 'DateTime::Format::ISO8601', '0.14';
