requires 'Amazon::S3', '0.45';
requires 'DBD::mysql', '4.050';
requires 'DBI', '1.643';
requires 'JSON', '4.02';
requires 'JSON::XS', '4.02';
requires 'Text::CSV', '2.00';
requires 'Text::CSV_XS', '1.44';
requires 'LWP::Protocol::https', '6.09';
